server:
  port: 8080
  session:
    timeout: 1800
  undertow:
    worker-threads: 500

debug:
  false

spring:
  application:
    name: DistributionAPI
  http:
    encoding: UTF-8
    enabled: true
endpoints:
  enabled: true
  sensitive: false
  shutdown:
    enabled: false
    id: 1
    path: /shutdown
    sensitive: true